### ISSUE TITLE
Add infinite scroll option

### ISSUE THREAD

**Issue by marktmcgrath** [a8cteam51/query-loop-load-more#3]
It would be great if we could add an infinite scroll option to the plugin.

This would essentially replace the need for the "learn more" button and would simply load more posts automatically as a user scrolls down the page.

**Comment by tommusrhodus** [comment]
In place and working https://a8c.slack.com/archives/C01M1J49Q75/p1687870154733629?thread_ts=1687781881.366609&cid=C01M1J49Q75 🥳

Closing
